<a href="https://colab.research.google.com/github/triastrale/stemming/blob/nazief_adriani/StemmingIndonesia_Kel7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import re
from itertools import combinations

In [ ]:
# Baca dataset
df = pd.read_csv('Dataset_BINDO - Sheet1.csv')
df

,judul,isi
0,"4 Calon Kuat Penerus Paus Fransiskus, Ada dari...","Jakarta, CNN Indonesia -- Kepergian mendiang P..."
1,"AS Soro QRIS & GPN dalam Negosiasi Dagang, Ini...","Jakarta, CNBC Indonesia - Penggunaan sistem pe..."
2,Dampak Tarif Resiprokal Trump terhadap Industr...,"TEMPO.CO, Jakarta - Ekonom dari Ins tute for D..."
3,Dilema Persalinan Caesar di Era JKN: Antara Ha...,Beredarnya narasi bahwa operasi caesar tidak a...
4,"Dugaan Ekspoitasi Mantan Pemain Sirkus, Komisi...",Komisi III DPR mengundang sejumlah mantan pema...
5,Eksistensi Media Massa Nasional,Berbicara tentang media arus utama (mainstream...
6,Global South dan Ilusi Netralitas,"Mereka, para negara peserta Konferensi Asia-Af..."
7,Gonjang-ganjing Isu Evakuasi Warga Gaza ke Ind...,Presiden RI Prabowo Subianto pada pekan kedua ...
8,Makna Kebersamaan dalam Tradisi Mengibung dan ...,Tradisi Megibung dari Bali dan Kembul Bujana d...
9,Peran Bimbingan dan Konseling Dalam Pendidikan...,WEBINAR HUT ABKIN ke-49 II PD ABKIN JAWA TENGA...
10,Senarai Catatan di Hari Buku Sedunia dan Tanta...,Tanggal ini dipilih sebagai penghormatan kepad...
11,Bagaimana mengubah ‘eco-anxiety’ kita menjadi ...,Perubahan iklim hingga bencana alam yang terja...
12,Benarkah anak-anak butuh mata pelajaran koding...,"Februari 2025 lalu, Badan Standar, Kurikulum, ..."
13,Kecanduan media sosial bikin anak muda rentan ...,Kamu mungkin terbiasa menghabiskan waktu berja...
14,Ini 5 Bahaya Makanan Junk Food yang Perlu Diwa...,"Halodoc, Jakarta – Junk food alias makanan ce..."
15,Ketika Jas Putih Menjadi Tameng: Menggugat Sis...,"Beberapa waktu lalu, publik dikejutkan oleh pe..."
16,Rupiah di Tengah Perekonomian yang Tertekan,Nilai tukar rupiah terus mengalami tekanan cuk...
17,Okupasi Senyap Ruang Angkasa,Tanpa adanya rezim internasional yang kuat dan...
18,Pendidikan Dasar dan Menengah yang Bermutu unt...,Menteri Pendidikan Dasar dan Menengah Abdul Mu...
19,Teknologi Dirgantara Untuk Operasi Bantuan Kem...,Dinamika global terus bergerak diwarnai ketega...
20,China Akan Balas Negara-negara yang Bekerja Sa...,China memperingatkan akan membalas negara-nega...
21,Rupiah di Tengah Perekonomian yang Tertekan,Nilai tukar rupiah terus mengalami tekanan cuk...
22,Korupsi yang Menjegal Daerah,Kejaksaan Tinggi Banten menahan Kepala Dinas L...
23,Melanjutkan Cita-cita Politik Kartini,Melanjutkan Cita-cita Politik Kartini\n\nKarti...
24,Merawat Kartini di Kebun Nirkertas,“Saya mau bekerja bukan karena ingin menjadi b...
25,Peran Media Massa dalam Membentuk Opini Publik,Media massa memiliki peran yang sangat penting...
26,Ragam Keluhan Mitra MBG: Menalangi Biaya hingg...,Sebagian mitra Makan bergizi Gratis mengeluhka...
27,Robot Ikut Lomba Lari\r,Lomba lari setengah maraton di Beijing yang di...
28,TKDN dan Negosiasi Dagang RI-AS,Beberapa asosiasi usaha dan pengamat mengkhawa...
29,"Untuk Bantu Pahami Matematika, Anak Perlu Meto...",Kementerian Komunikasi dan Informatika (Kominf...

In [ ]:
# List imbuhan dan akhiran
IMBUHAN = ['peng', 'pem', 'peny', 'per','pen', 'ber', 'meny', 'meng', 'mem', 'men', 'me', 'ter', 'nya', 'se','an', 'ku', 'mu', 'kan']
AKHIRAN = ['an', 'nya', 'ku', 'mu', 'kan']

# Fungsi untuk stemming satu teks
def clean_text(text):
    if pd.isna(text):  # Kalau kosong, langsung return kosong
        return ''
    clean_words = []
    new_string = re.sub(r'[^\w\s]', '', text)  # Hapus tanda baca
    words = new_string.split()

    for w in words:
        clean_word = w.lower()

        # Bersihkan imbuhan awal
        for imbuh in IMBUHAN:
            if re.match(imbuh, clean_word):
                clean_word = re.sub(f"^{imbuh}", '', clean_word)

        # Bersihkan akhiran
        for akhir in AKHIRAN:
            clean_word = re.sub(f"{akhir}$", '', clean_word)

        clean_words.append(clean_word)

    return " ".join(clean_words)

# Terapkan fungsi ke kolom 'isi'
df['isi_clean'] = df['isi'].apply(clean_text)
df['isi_clean']

0     jakarta cnn indonesia kepergi diang paus frans...
1     jakarta cnbc indonesia guna sistem bayar indon...
2     tempoco jakarta ekonom dari ins tute for devel...
3     edar narasi bahwa operasi caesar tidak ak dita...
4     komisi iii dpr undang jumlah mant ain sirkus o...
5     bicara tentang dia arus utama mainstream hari ...
6     reka para negara peserta konferensi asiaafrika...
7     presiden ri prabowo subianto pada pek kedua ap...
8     tradisi gibung dari bali d kembul bujana dari ...
9     webinar hut abkin ke49 ii pd abkin jawa tengah...
10    tanggal ini dipilih bagai hormat kepada dua sa...
11    ubah iklim hingga bencana alam yang jadi di ma...
12    februari 2025 lalu bad standar rikulum d asesm...
13    ka ngkin biasa habisk waktu jamjam lancar di d...
14    halodoc jakarta junk food alias ma cepat saji ...
15    beberapa waktu lalu publik dikejutk oleh ita t...
16    nilai tukar rupiah us alami te cukup at bebera...
17    tanpa ada rezim internasional yang at d dapat ...
18    i didik dasar d engah abdul ti dalam rapat ker...
19    dinamika global us gerak diwarnai ketegang pol...
20    china peringatk ak balas negaranegara yang bek...
21    nilai tukar rupiah us alami te cukup at bebera...
22    kejaksa tinggi banten ah kepala dinas lingkung...
23    lanjutk citacita politik kartini kartini tidak...
24    saya mau bekerja buk karena ingin jadi besar a...
25    dia massa iliki  yang sangat ting dalam bentuk...
26    bagi mitra mak gizi gratis eluhk tidak dapat b...
27    lomba lari tengah maraton di beijing yang diik...
28    beberapa asosiasi usaha d amat khawatirk relak...
29    kementeri komunikasi d informatika kominfo ril...
Name: isi_clean, dtype: object

In [ ]:
#Tokenizing
def tokenizing(input):
  input = input.replace(".", "")
  input = input.replace(",", "")
  input = input.replace(":", "")
  input = input.replace("-", " ")
  input = input.replace("?", "")
  input = input.replace("!", "")
  input = input.replace("(", "")
  input = input.replace(")", "")
  input = input.replace("[", "")
  input = input.replace("]", "")
  input = input.replace("{", "")
  input = input.replace("}", "")
  input = input.replace("'", "")
  input = input.replace('"', "")
  input = input.replace("/", "")
  return input

In [ ]:
#Pemisahan kata berdasarkan spasi
def split_words(words):
  return words.split(' ')

In [ ]:
#Stopwords
# open stopword

def stop_word(word):

  f = open('id.stopwords.02.01.2016.txt')
  s_word = f.read()

  if word not in s_word :
    return word


  f.close()

In [ ]:
#Kamus
kamus_clean = []

with open('kata-dasar-indonesia.txt') as f:
  kamus = f.read()
  kamus = kamus.split(' ')

  for w in kamus:

    rx = re.findall(r'[^\n]+$', w)

    kamus_clean.append(rx[0])

AKAR_KATA = []

def kamus_word(word='tes'):

    # kamus = map(clean_word, kamus)
    if word in kamus_clean:
      AKAR_KATA.append(word)
      return None
    return word

In [ ]:
#Hapus Infleksional Suffix
def hapus_infleksional_suffiks(word):
  # akhiran -lah, -kah, -nya, -tah, -pun
  if word.endswith('lah') or word.endswith('kah') or word.endswith('nya') or word.endswith('tah') or word.endswith('pun'):
    word = word[0 : len(word) - 3]

    # check if word exist in kamus
    word_check = kamus_word(word)

    return word_check

  # akhiran -ku, -mu
  elif word.endswith('ku') or word.endswith('mu'):
    word = word[0 : len(word) - 2]

    # check if word exist in kamus
    word_check = kamus_word(word)
    return word_check

  return word

In [ ]:
#Hapus derivation suffixes

def hapus_derivation_suffiks(word):
    # akhiran kan
  if word.endswith('kan'):
    word = word[0 : len(word) - 3]

    # check if word exist in kamus
    word_check = kamus_word(word)
    return word_check

  # akhiran i
  if word.endswith('i'):
    word = word[0 : len(word) - 1]

    # check if word exist in kamus
    word_check = kamus_word(word)
    return word_check

  # akhiran an
  if word.endswith('an'):
    word = word[0 : len(word) - 2]

    # check if word exist in kamus
    word_check = kamus_word(word)
    return word_check


  return word

In [ ]:
#Hapus derivation prefiks

def hapus_derivation_prefiks(word):
  # awalan mempel-
  if (word.startswith('mempel')) and (len(word) > 6):
    sub_word = word[6:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check

    return word_check

  # awalan memper-
  if (word.startswith('memper')) and (len(word) > 6):
    sub_word = word[6:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:

      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check

    return word_check

  # awalan diper-, keber-, keter-
  if (word.startswith('diper') or word.startswith('keber') or word.startswith('keter')) and (len(word) > 5):
    sub_word = word[5:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:

      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check
    return word_check

  # awalan meng-, peng-
  if (word.startswith('meng') or word.startswith('peng')) and (len(word) > 4):
    sub_word = word[4:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)
      # check word again in kamus
      word_check = kamus_word(word_pref_suff)

      if word_check != None:
        # add 'k' in front word
        sub_word = 'k' + word_check

        # check word again in kamus
        word_check = kamus_word(sub_word)

        if word_check != None:
          # check word in derivation suffiks
          word_pref_suff_k = hapus_derivation_suffiks(word_check)

          # check word again in kamus after add k in front
          word_check = kamus_word(word_pref_suff_k)
          return word_check

    return word_check

  # awalan meny-, peny-
  if (word.startswith('meny') or word.startswith('peny')) and (len(word) > 4):
    sub_word = word[4:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      if word_check != None:

        # add 's' in front word
        sub_word = 's' + word_check

        # check word again in kamus
        word_check = kamus_word(sub_word)
        if word_check != None:
          # check word in derivation suffiks
          word_pref_suff_s = hapus_derivation_suffiks(word_check)

          # check word again in kamus after add s in front
          word_check = kamus_word(word_pref_suff_s)
          return word_check
    return word_check

  # awalan mel-, mer-, pel-, per-
  if (word.startswith('mel') or word.startswith('mer') or word.startswith('pel') or word.startswith('per')) and (len(word) > 3):
    sub_word = word[3:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check
    return word_check

  # awalan men-, pen-
  if (word.startswith('men') or word.startswith('pen')) and (len(word) > 3):
    sub_word = word[3:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      if word_check != None:
        # add 's' in front word
        sub_word = 't' + word_check

        # check word again in kamus
        word_check = kamus_word(sub_word)

        if word_check != None:
          # check word in derivation suffiks
          word_pref_suff_t = hapus_derivation_suffiks(word_check)

          # check word again in kamus after add s in front
          word_check = kamus_word(word_pref_suff_t)
          return word_check
    return word_check


  # awalan mem-, pem-
  if (word.startswith('mem') or word.startswith('pem')) and (len(word) > 3):
    sub_word = word[3:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      if word_check != None:
        # add 's' in front word
        sub_word = 'p' + word_check

        # check word again in kamus
        word_check = kamus_word(sub_word)

        if word_check != None:
          # check word in derivation suffiks
          word_pref_suff_p = hapus_derivation_suffiks(word_check)

          # check word again in kamus after add s in front
          word_check = kamus_word(word_pref_suff_p)
          return word_check
    return word_check
  # awalan bel-, ber-, tel-, ter-
  if (word.startswith('bel') or word.startswith('ber') or word.startswith('tel') or word.startswith('ter')) and (len(word) > 3):
    sub_word = word[3:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check

    return word_check

  # tipe awalan ke 1 : di-, ke-, se-
  if (word.startswith('di') or word.startswith('ke') or word.startswith('se')) and (len(word) > 2):
    sub_word = word[2:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check
    return word_check


  # tipe awalan ke 2 : be-, te-
  if (word.startswith('be') or word.startswith('te')) and (len(word) > 2):
    sub_word = word[2:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)
    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check

    return word_check

  # tipe awalan ke 3 : me-, pe-
  if (word.startswith('me') or word.startswith('pe')) and (len(word) > 2):
    sub_word = word[2:]
    # check if word exist in kamus
    word_check = kamus_word(sub_word)

    if word_check != None:
      # check word in derivation suffiks
      word_pref_suff = hapus_derivation_suffiks(word_check)

      # check word again in kamus
      word_check = kamus_word(word_pref_suff)
      return word_check

    return word_check

In [ ]:
with open('Dataset_BINDO - Sheet1.csv') as f:
  words = f.read()
  # print(f'jumlah kata awal : {len(words)}')

  # lower words
  words = words.lower()

  # tokenizing
  words = tokenizing(words)
  # print(f'jumlah kata setelah tokenizing : {len(words)}')

  # split words
  words = words.split(' ')
  print(f'jumlah kata awal : {len(words)}')


  list_stop_words = []
  # stop word
  for w in words:
    word = stop_word(w)
    if word != None:
      list_stop_words.append(word)

  print(f'jumlah kata setelah stop word : {len(list_stop_words)}')

  list_not_in_kamus_words = []
  # kamus word
  for w in list_stop_words:
    word = kamus_word(w)
    if word != None:
      list_not_in_kamus_words.append(word)

  print(f'jumlah kata setelah kamus : {len(list_not_in_kamus_words)}')
  print(f'Akar kata {len(AKAR_KATA)}')

  # hapus infleksional suffiks
  list_not_infleksional_suffiks = []

  for w in list_not_in_kamus_words:
    word = hapus_infleksional_suffiks(w)
    if word != None:
      list_not_infleksional_suffiks.append(word)

  print(f'jumlah kata setelah infleksional suffiks : {len(list_not_infleksional_suffiks)}')
  print(f'Akar kata {len(AKAR_KATA)}')

  # hapus derivation suffiks
  list_not_derivation_suffiks = []

  for w in list_not_infleksional_suffiks:
    word = hapus_derivation_suffiks(w)
    if word != None:
      list_not_derivation_suffiks.append(word)

  print(f'jumlah kata setelah derivation suffiks : {len(list_not_derivation_suffiks)}')
  print(f'Akar kata {len(AKAR_KATA)}')

  # hapus derivation prefix
  list_not_in_kamus = []

  for w in list_not_derivation_suffiks:
    word = hapus_derivation_prefiks(w)
    if word != None:
      list_not_in_kamus.append(word)

  print(f'jumlah kata setelah derivation prefiks : {len(list_not_in_kamus)}')
  print(f'Akar kata {len(AKAR_KATA)}')

  print(f'Kata yang tak ada di kamus {list_not_in_kamus}')

jumlah kata awal : 22029
jumlah kata setelah stop word : 12757
jumlah kata setelah kamus : 7191
Akar kata 5566
jumlah kata setelah infleksional suffiks : 7057
Akar kata 5700
jumlah kata setelah derivation suffiks : 6587
Akar kata 6170
jumlah kata setelah derivation prefiks : 1008
Akar kata 9281
Kata yang tak ada di kamus ['nin', 'puncul', 'lanjutnya\nsejum', 'potens', 'jarah\n\nkardinal', 'evisi\n\nbah', 'kerja\n\nedward', 'kgantikannya\n\nkardinal', 'kaster', 'egraph\n\nnamun', 'hat', 'pemimpin', 'tasihat', 'tasihat', 'pilih\n\nkardinal', 'sebut\n\npaus', 'nediktus', 'tasihat', 'ebut', 'ketahu', 'tila', 'tingg', 'ring\n\npeter', 'kgant', 'tila', 'pemimpin', 'caya', 'ttin\n\nsecara', 'kristen', 'sebut\n\nnamun', 'pilik', 'kungsi\n\nerdo', 'jal', 'kgant', 'posis', 'salahan\n\nnamun', 'ug', 'tdonca', 'kgant', 'tdidikan\n\ndar', 'pilik', 'tingg', 'pilik', 'kgant', 'tola', 'koordinas', 'ob', 'onggar', 'ob', 'prediks', 'kecual', 'tila', 'khawa', 'osot', 'tenagakerja', 'prediks', 'tila', 'ebih', 'potens', 'la', 'potens', 'puncul', 'teliti\nkesehat', 'tila', 'panfaat', 'sehatan\n\nsejak', 'uncur', 'dis\n\nnamun', 'puncul', 'ring\nkal', 'la', 'tentuan\nd', 'rasa\nterbaik', 'mestinya\ntetap', 'dis\n\nsecara', 'rius\nsepert', 'ni\nnamun', 'ebih', 'cara\nsignifikan\n\nd', 'pendid', 'pilik', 'indikas', 'dishield', 'lukan\n\npenulis', 'dis”', 'rap\nmenjad', 'pahami\nhak', 'besar\nd', 'onjak', 'kadar\nperkara', 'hatikan\nkeberlanjut', 'kait\npersalin', 'bagai\npilih', 'salinan\nnormal', 'operas', 'naga\nmedis', 'hingga\nmemicu', 'simpangsiur', 'seimbang', 'pangku\nkepentingan—pemerin', 'serta—perlu', 'sinerg', 'eksploitas', 'nin', 'partisipas', 'komunikas', 'nin', 'eksploitas', 'tindaklanjut', 'buda', 'pilik', 'pekerja', 'buda', 'tdid', 'koordinas', 'menterianlembaga', 'tindaklanjut', 'atih', 'pb', 'keksploitas', 'dsos', 'ampau', 'osot', 'amping', 'tdasar\nada', 'garisbawah', 'dsos', 'kambilalih', 'aih', 'embaga', 'operas', 'kesamping', 'dsos', 'kesamping', 'dsos', 'bencian\ndalam', 'kantisipas', 'dsos', 'karakter', 'dsos', 'embaga', 'dsos', 'dsos', 'dsos\nproteks', 'mest', 'dsos', 'law', 'dsos', 'adab\nmempertah', 'pilik', 'sesua', 'limpahruah', 'laya', 'dsos', 'mest', 'dsos', 'law', 'dsos', 'mest', 'panfaat', 'la', 'hat\n\nglobal', 'dir', 'be', 'kuasaan\n\nnamun', 'tahan\n\nkapitalisme', 'emah;', 'sesua', 'pilik', 'pilik', 'operas', 'am\n\nkita', 'piha', 'piha', 'saat\n\ndalam', 't', 'tambangan\n\nd', 'uncur', 'uas', 'ksiko', 'tawar;', 'encana', 'orientas', 'anjut', 'piha', 'tcar', 'seimbang', 'umus', 'pilik', 'anggeng', 'padai;', 'tegosias', 'tcar', 'tcar', 'hent', 'apresias', 'belumnya\n\nin', 'pemimpin', 'terimanya\n\npresiden', 'elokas', 'ngah”', 'nant', 'terimanya\n\nas', 'sebut\n\nwitkoff', 'unding', 'sebut\n\nnamun', 'tola', 'sebut\n\nmesk', 'kgelinding\n\nadu', 'tola', 'adops', 'perangkap', 'eka\n\nmaka', 'kevakuas', 'evakuas', 'lesai\n\nproses', 'kungs', 'caya', 'kevakuas', 'mbul', 'janatradis', 'gibung', 'mbul', 'kedar', 'bag', 'gibung', 'tut', 'gibung', 'ang\n\n\ntradis', 'setara', 'gibung', 'luarga\n\n\nkata', 'gibung', 'bag', 'samaan\n\n\natur', 'gibung', 'ekat', 'mbul', 'mbul', 'aya', 'iput', 'mbul', 'tikmat', 'bag', 'pilik', 'tdalam\n\n\nsejarah', 'mbul', 'caya', 'gibung', 'mbul', 'bag', 'bag', 'gibung', 'mbul', 'sederhanaan\n\n\nd', 'gibung', 'mbul', 'pudar\n\n\nkekhawatir', 'gibung', 'mbul', 'sajiannya\n\n\nwury', 'perhat', 'gibung', 'mbul', 'estar', 'gibung', 'mbul', 'gibung', 'mbul', 'ahir', 'gibung', 'mbul', 'har', 'tdid', 'kert', 'tdid', 'pilik', 'tdid', 'tdid', 'pilik', 'pilik', 'ketahu', 'pbentu', 'pilik', 'fungs', 'ampil', 'interaks', 'tdid', 'perintah\n\n\npendid', 'tdid', 'tdid', 'tidakmerata', 'tdid', 'perintah\n\n\nmenanggap', 'tdid', 'mendikdasmen', 'tdid', 'fungs', 'kontribus', 'karakter', 'siplintanggung', 'rasetika', 'ampil', 'tdeteks', 'nangnyam', 'pbully', 'undung', 'tunju', 'tdid', 'tdid', 'ibat', 'hargai\nsenara', 'adops', 'ketahu', 'w', 'nsorik', 'kadops', 'tdidikan\npemerin', 'gital\n\n\nkecenderung', 'oritik', 'pbelajar', 'pudah', 'konsentras', 'telit', 'mdikbud', 'oritis', 'iput', 'adaptas', 'pbaca\nprogram', 'tdid', 'pbelajar', 'tdalam\nmesk', 'tdid', 'ketahu', 'adaban\nbagaimana', 'pilik', 'eka\nlalu', 'konsums', 'is', 'simistis\nuntuk', 'is', 'estar', 'pilik', 'hubungan\n3', 'partisipas', 'sar\nsebuah', 'lf', 'pilik', 'suarakannya\nin', 'pberdaya', 'atih', 'caya', 'dampak\nper', 'dsos\nsa', 'banya', 'dsos', 'encana', 'kontribus', 'kolaboras', 'kadvokas', 'sar\nrasa', 'dsos', 'kolahfebruar', 'tdid', 'tdid', 'mendikdasmen', 'ilis', 'pbelajar', 'sebut\npemerin', 'mendikdasmen', 'pilik', 'ata', 'tdid', 'paka', 'knologi\nselain', 'ibat', 'tentu\nrute', 'tdeteks', 'interaks', 'pbelajar', 'pilik', 'pinggirkan\nmenggeser', 'tdidikan\nkarakter', 'orientas', 'kuasaan\napabila', 'pbelajar', 'gital—yang', 'kuasa—maka', 'tdid', 'abaikan\nselain', 'ampil', 'korb', 'ampil', 'turun\nurgens', 'tdid', 'pberdaya', 'seluruhan\njika', 'isiko', 'pbelajar', 'atih', 'tdid', 'tdid', 'perdeka', 'pilik', 'pbelajar', 'ampil', 'telit', 'ampil', 'panfaat', 'ampil', 'gital\nalih', 'atih', 'kelanjut', 'kadops', 'pbelajaran\nteknolog', 'paka', 'tdid', 'pbelajar', 'potens', 'ketahuan\nkecandu', 'kgal', 'isiko', 'ttalmu\nsa', 'puntah', 'konsums', 'bukt', 'telit', 'sebut\nperkembang', 'gemu', 'kinspiras', 'pilik', 'hat\nbak', 'isiko', 'pilik', 'konsums', 'sehatan\nganggu', 'pilik', 'serupa', 'epas', 'pilik', 'hat\nbahaya', 'abaikan\nremaja', 'isiko', 'isiko', 'rius\nkasus', 'isiko', 'isiko', 'har', 'minggu', 'bulan\nbila', 'sebut\n2', 'sosialisas', 'interaks', 'jal', 'ajut', 'tar', 'kebun\n3', 'gital\nlebih', 'm', 'ekomendas', 'ekomedas', 'encana', 'pat\nganggu', 'waspadaihalodoc', 'konsums', 'omer', 'canduan\njunk', 'angsang', 'konsums', 'dicine', 'konsums', 'ni\n\n5', 'konsums', 'gant', 'hat\nma', 'ma', 'konsums', 'sadaran\n\nhindar', 'kemil', 'kemud', 'hat\n\nma', 'ewat', 'tdid', 'ibat', 'tdid', 'tdid', 'jal', 'tdid', 'jal', 'kkhawatirkan\n\nsebuah', 'pilik', 'kerja\nppds', 'pegawa', 'tdid', 'tdid', 'tdid', 'niorisme', 'tdid', 'hent', 'jalani\n\npadahal', 'tdid', 'tolerans', 'tdid', 'dokteran\n\nrelas', 'kawasan\nhal', 'pilik', 'apor', 'eceh', 'sonality', 'isiko', 'kidentifikas', 'sembuny', 'tdid', 'tdid', 'terapkan\n\n1', 'apor', 'tdid', 'pilik', 'pilik', 'kintervens', 'apor', 'kala\nasesmen', 'tdid', 'ban\ntuju', 'tcar', 'atih', 'rawat\n\nmenanam', 'tdid', 'telad', 'hat\n\nkita', 'intimidas', 'adilan\n\n2', 'ttoring', 'ttoring', 'tdid', 'atih', 'ras”\n\n3', 'mester\nsama', 'tdid', 'kelanjutan\n\nmendidik', 'ampil', 'pproduks', 'kgant', 'utuhnya\n\njika', 'hent', 'selamatkan\nrupiah', 'tekannila', 'sen\nkebija', 'giz', 'emah', 'emah', 'puncul', 'salahguna', 'taik', 'agu', 'emah', 'emah', 'banya', 'jal', 'emah', 'kelanjut', 'tidakpast', 'emah', 'ekonomian\napalag', 'dagangan\nkewibawa', 'bijakan\nnila', 'emah', 'emah', 'edam', 'ebih', 'emah', 'emah', 'kelanjut', 'bankan\nkondis', 'jal', 'sulitan\nkeada', 'emah', 'bijakan\nb', 'ban\nvolume', 'simp', 'negosias', 'simp', 'tdominas', 'uncur', 'gakonstelasinya\n\nruang', 'partisipas', 'ayang', 'paka', 'pemil', 'pemil', 'pemil', 'kelolaan\n\nmereka', 'pilik', 'pemil', 'am\n\nparadoks', 'puncul', 'tandatang', 'sebut\n\noleh', 'ekat', 'rved', 'ingkup', 'pemil', 'pilik\n\nsementara', 'aksana', 'sebut\n\nhukum', 'kin', 'adaptasi\noleh', 'katalisas', 'koordinas', 'mpurna\n\nmisal', 'pbentu', 'is', 'ibat', 'adaptas', 'pinimal', 'panfaat', 'kesinambung', 'potens', 'emah', 'kkaj', 'tdatang\n\ndibutuh', 'pemil', 'pentingan\n\nuntuk', 'kelanjut', 'pbentu', 'buka\npendid', 'tdid', 'tdid', 'tengah\n\nprogram', 'tdid', 'ata', 'tdid', 'tdid', 'mua\n\nprogram', 'tdid', 'pbentu', 'tdid', 'tdid', 'ibat', 'tdidikan\n\nketiga', 'atih', 'tdid', 'ampil', 'ni\n\nkelima', 'estar', 'tdikdasmen', 'tdid', 'pencil\n\nluas', 'tdid', 'tdid', 'tdid', 'tdid', 'tdid', 'pencil\n\nseko', 'tdid', 'tdidikan\n\npemerin', 'uncur', 'pencil\n\nnamun', 'tdid', 'atih', 'kelanjut', 'tikmat', 'tdid', 'tara\n\nguru', 'pengalam', 'telit', 'panfaat', 'pbelajar', 'ampil', 'pbelajar', 'pilik', 'sar\n\nguru', 'atih', 'ata', 'pilik', 'tdidikan\n\nfaktor', 'sendir', 'kabd', 'pencil\n\nuntuk', 'atih', 'atih', 'umah', 'tdid', 'tdid', 'sebut\n\nsebaga', 'tdid', 'pberdaya', 'tdidikan\n\nagar', 'atih', 'ampil', 'tdidikan\n\nmengait', 'tdid', 'ibat', 'daulatan\n\nmelalu', 'ni\n\nkesimpul', 'tdid', 'ata', 'perintah\n\ndeng', 'kelanjut', 'tdid', 'manusiaandinamika', 'ap', 'tingkat\nsituas', 'pilik', 'siapsiaga', 'kin', 'saster', 'manusiaan\ntn', 'siapsiaga', 'kevakuas', 'isolas', 'komunikasi\nperkembang', 'manusiaan\ncontoh', 'tila', 'akses\npengguna', 'bukt', 'selamatan\nmisal', 'ibat', 'celakaan\nhal', 'akses\nselain', 'pilik', 'isolas', 'bag', 'bag', 'ketahu', 'kalaman\ndalam', 'siapsiaga', 'espons', 'intas', 'siapsiaga', 'panfaat', 'ndirian\nmelalu', 'bag', 'ketahu', 'knologi;', 'pinimal', 'ncana;', 'manusiaan\nchina', 'ijing', 'ibat', 'nin', 'encana', 'taik', 'korb', 'salahguna', 'undung', 'ijing', 'undung', 'kgant', 'tekannila', 'sen\nkebija', 'giz', 'emah', 'emah', 'puncul', 'salahguna', 'taik', 'agu', 'emah', 'emah', 'banya', 'jal', 'emah', 'kelanjut', 'tidakpast', 'emah', 'ekonomian\napalag', 'dagangan\nkewibawa', 'bijakan\nnila', 'emah', 'emah', 'edam', 'ebih', 'emah', 'emah', 'kelanjut', 'bankan\nkondis', 'jal', 'sulitan\nkeada', 'emah', 'bijakan\nb', 'ban\nvolume', 'simp', 'negosias', 'simp', 'pilik', 'sangka\n\nsebelum', 'marang', 'marang', 'eda\n\nkorups', 'pbudaya\n\ndalam', 'korups', 'prediks', 'ppraktikkan\npolitik', 'tindas\n\nsetiap', 'anda', 'etak', 'bangsaan\nd', 'tdid', 'setara', 'deka\n\ndalam', 'anda', '\npendid', 'tdid', 'anda', 'ancis', 'sar\nsepert', 'tidakadil', 'tebal', '\n42', 'pilik', 'ampau', 'setara', 'ring\nkita', 'hidupan\n\nlapor', 'tempatkan\nindonesia', 'setara', 'cara\nproporsional', 'tunjukkan\nbahwa', 'pilik', 'saran\nuntuk', 'taik', 'kungkapkan\nperjuang', 'tdid', 'ppraktikkan\npolitik', 'anda', 'cara\nbersama', 'kunc', 'empuan\ndalam', 'pemimpin', 'empuan\nangka', 'piha', 'hent', 'empuan\nyang', 'pbuatan\nkeputus', 'setara', 'ata', 'keadil', 'bukt', 'tdid', 'miskinan\nberbasis', 'jal', 'sany', 'tdid', 'empuan\n\nlang', 'munculan\npemimpin', 'tdukung\nmemberdaya', 'empuan\n\nd', 'kevaluas', 'penuhi\nketentu', 'sebut\n\naspek', 'empuan\nmengingat', 'alui\nskema', 'pbuka\nruang', 'tdid', 'tdid', 'tdid', 'lu\ndiperluas', 'empuan\n\nkartin', 'tavigasi\nkompleksitas', 'ubah\n\nupaya', 'setara', 'ainkan\nalat', 'encana', 'encana', 'perti\nrpjmn', 'perintah\ndaerah', 'mua\n\nkartin', 'putusan\n\npotens', 'engkap', 'ainkan\ntentang', 'keadilan\nselamat', 'benaran”', 'sehar', 'ekat', 'bas\n\nkartin', 'pikir\n\nkartin', 'bakt', 'terima”', 'prestas', 'utia', 'pindah—menyapa', 'seharian\n\nkita', 'kgal', 'tdid', 'pemimpin', 'timpangan—d', 'pudah', 'jati\n\nkita', 'estar', 'har', 'har', 'tuh\n\nperjuang', 'pprovokas', 'ampau', 'tidakadil', 'sembuny', 'goyahkan\n\nbagaimana', 'setara', 'kali”', 'pilik', 'pilik', 'eka\nmedia', 'kin', 'pilik', 'kelanjut', 'pikiran\nmedia', 'apor', 'tidakadil', 'pilik', 'setara', 'pilik', 'kedukas', 'tdid', 'ketahu', 'ketahu', 'orientas', 'pilik', 'kemb', 'seimbang', 'nsationalisme', 'pilik', 'pbentu', 'pbentu', 'pilik', 'pilik', 'verifikas', 'kevaluas', 'pilik', 'pilik', 'bag', 'hat\nmedia', 'pbentu', 'pbentu', 'imbang\nragam', 'giz', 'mpoco', 'giz', 'mulai\n\nmitra', 'giz', 'operas', 'giz', 'bayar\ntata', 'har', 'giz', 'nin', 'tidakpast', 'pb', 'gawa', 'konfirmas', 'giz', 'aksana', 'giz', 'nin', 'ijing', 'gigihan\nchina', 'knologi\n\najang', 'ijing', 'sertanya\ntetap', 'varias', 'pilik', 'lar', 'kuj', 'laporkan\nsejum', 'gant', 'serta\ndigant', 'penang', 'ijing', 'banya', '\nkategor', 'penang', 'tit\n\nkeikutserta', 'serupa', 'past', 'mampuan\nmenjaga', 'tdid', '\nbidang', 'integras', 'la', 'tanyakan\n\nkalang', 'unak', 'onggar', 'ug', 'kuntungkan\n\nkebija', 'ilis', 'tdid', 'chnology', 'pbelajar', 'tdid', 'tdid', 'senangkan”', 'ang', 'nin', 'ampil', 'aih', 'pbelajar', 'iput', 'pilik', 'motivas', 'tikmat', 'ampil', 'har', 'pilik', 'ampil', 'pbelajar', 'pilik', 'tdid', 'sebut”']

In [ ]:
print(AKAR_KATA)
print(len(AKAR_KATA))

['calon', 'kuat', 'paus', 'tetangga', 'mendiang', 'paus', 'umat', 'dunia', 'nama', 'kardinal', 'calon', 'kuat', 'paus', 'nama', 'sejarah', 'paus', 'kawasan', 'nama', 'kardinal', 'gadang', 'kuat', 'paus', 'umat', 'kandidat', 'bursa', 'paus', 'pria', 'paus', 'populer', 'kaum', 'progresif', 'gereja', 'hangat', 'progresif', 'mendiang', 'paus', 'reformis', 'mendiang', 'paus', 'tinggal', 'seminari', 'kamar', 'uskup', 'mobil', 'bus', 'pakar', 'buku', 'kardinal', 'favorit', 'paus', 'kepala', 'gereja', 'kandidat', 'kuat', 'muda', 'paus', 'kardinal', 'cenderung', 'hati', 'paus', 'relatif', 'muda', 'paus', 'relatif', 'muda', 'kardinal', 'kunci', 'paus', 'isu', 'isu', 'iklim', 'sosial', 'kardinal', 'calon', 'kuat', 'umat', 'dunia', 'sejarah', 'paus', 'kulit', 'hitam', 'uskup', 'agung', 'cape', 'paus', 'kardinal', 'sejarah', 'negara', 'kepala', 'dewan', 'lembaga', 'sosial', 'asasi', 'manusia', 'paus', 'isu', 'isu', 'iklim', 'luas', 'konferensi', 'internasional', 'forum', 'ekonomi', 'paus', 'departemen', 'kardinal', 'kantor', 'langkah', 'departemen', 'pengaruh', 'kardinal', 'akademi', 'bidang', 'ilmu', 'ilmu', 'wawancara', 'paus', 'gereja', 'tampil', 'media', 'konservatif', 'muncul', 'nama', 'kardinal', 'uskup', 'agung', 'calon', 'kuat', 'paus', 'kandidat', 'kuat', 'konservatif', 'gereja', 'kardinal', 'ahli', 'hukum', 'kanon', 'dab', 'mahir', 'hukum', 'umat', 'gereja', 'kondisi', 'hukum', 'gerejawi', 'paus', 'sosok', 'teologis', 'konservatif', 'akar', 'benua', 'pragmatis', 'paus', 'rohaniwan', 'krisis', 'migran', 'paus', 'gereja', 'gereja', 'bentuk', 'manusia', 'nasionalis', 'perdana', 'menteri', 'negara', 'perdana', 'menteri', 'kandidat', 'perang', 'netral', 'dialog', 'imam', 'serikat', 'buku', 'diplomat', 'kompeten', 'otak', 'diplomasi', 'internasional', 'paus', 'akibat', 'skandal', 'properti', 'gedung', 'bekas', 'kompeten', 'proses', 'pastor', 'kardinal', 'nama', 'nama', 'cocok', 'umat', 'muncul', 'kandidat', 'kuat', 'paus', 'kaum', 'progresif', 'gereja', 'kardinal', 'pulau', 'paus', 'kepala', 'departemen', 'budaya', 'muncul', 'nama', 'kardinal', 'uskup', 'agung', 'calon', 'kuat', 'paus', 'sosok', 'progresif', 'paus', 'kawasan', 'kardinal', 'sekretaris', 'jenderal', 'sinode', 'uskup', 'posisi', 'gereja', 'paus', 'konservatif', 'kandidat', 'kompromi', 'nama', 'kardinal', 'gadang', 'kandidat', 'kuat', 'paus', 'ideologi', 'gender', 'radikalisme', 'negosiasi', 'dagang', 'sistem', 'gerbang', 'nasional', 'negosiasi', 'serikat', 'koordinator', 'bidang', 'bank', 'otoritas', 'jasa', 'konferensi', 'tarif', 'kartu', 'bank', 'perihal', 'wajib', 'silam', 'lokal', 'bisnis', 'sistem', 'transaksi', 'kartu', 'lokal', 'sumber', 'lobi', 'negara', 'alat', 'lokal', 'tulis', 'media', 'email', 'detail', 'email', 'halaman', 'informasi', 'via', 'surat', 'elektronik', 'email', 'dagang', 'laos', 'gana', 'transaksi', 'mayoritas', 'investor', 'transaksi', 'partner', 'lokal', 'transaksi', 'nasabah', 'laba', 'kartu', 'kredit', 'fasilitas', 'fasilitas', 'tarif', 'bea', 'produk', 'ekspor', 'fasilitas', 'tarif', 'resiprokal', 'industri', 'ekonom', 'hasan', 'dampak', 'tarif', 'resiprokal', 'serikat', 'rela', 'moderat', 'sisi', 'diskusi', 'publik', 'genderang', 'perang', 'komoditas', 'ekspor', 'tarif', 'resiprokal', 'produk', 'ekspor', 'teks', 'garmen', 'alas', 'kaki', 'sawit', 'dampak', 'industri', 'teks', 'produsen', 'serat', 'benang', 'teks', 'sisi', 'buruh', 'teks', 'konveksi', 'pabrik', 'industri', 'unit', 'tenaga', 'ribu', 'negara', 'ringan', 'level', 'tarif', 'serikat', 'posisi', 'mitra', 'dagang', 'persen', 'total', 'ekspor', 'pasar', 'negara', 'produk', 'tanah', 'surplus', 'signifikan', 'miliar', 'dolar', 'surplus', 'nilai', 'ekspor', 'nilai', 'negara', 'cenderung', 'kondisi', 'presiden', 'serikat', 'tarif', 'impor', 'tarif', 'impor', 'minimum', 'negara', 'dunia', 'langkah', 'industri', 'produk', 'negara', 'negara', 'dampak', 'tarif', 'persen', 'negara', 'daya', 'saing', 'produk', 'ekspor', 'pasar', 'negara', 'tarif', 'tarif', 'tarif', 'produk', 'ekspor', 'bentuk', 'ekonomi', 'negara', 'tenggara', 'tarif', 'persen', 'persen', 'persen', 'persen', 'tarif', 'negara', 'tarif', 'gedung', 'efisiensi', 'narasi', 'operasi', 'badan', 'hamil', 'calon', 'dokter', 'isu', 'publik', 'nasional', 'akses', 'drastis', 'signifikan', 'tenaga', 'akses', 'antarkelompok', 'wilayah', 'konsekuensi', 'masyarakat', 'otomatis', 'indikasi', 'fenomena', 'media', 'sosial', 'hamil', 'biaya', 'mandiri', 'klinik', 'dokter', 'perspektif', 'pasien', 'perspektif', 'sistem', 'dana', 'publik', 'efisiensi', 'indikasi', 'medis', 'operasi', 'nyawa', 'komplikasi', 'letak', 'janin', 'plasenta', 'berat', 'ketuban', 'pecah', 'indikasi', 'medis', 'persen', 'batas', 'bayi', 'tren', 'operasi', 'signifikan', 'persen', 'persen', 'survei', 'demografi', 'cenderung', 'ekonomi', 'tinggal', 'operasi', 'indikasi', 'negara', 'biaya', 'medis', 'kecuali', 'definisi', 'area', 'abu', 'abu', 'dokter', 'tenaga', 'manfaat', 'metode', 'transparan', 'hamil', 'sudut', 'pandang', 'sistem', 'operasi', 'mahal', 'daya', 'pos', 'persen', 'indikasi', 'moral', 'bebas', 'prosedur', 'dana', 'kontribusi', 'standar', 'indikasi', 'medis', 'ketat', 'defisit', 'kualitas', 'medis', 'konteks', 'publik', 'program', 'habis', 'pos', 'akses', 'daerah', 'individual', 'asas', 'gotong', 'narasi', 'edukasi', 'masyarakat', 'risiko', 'promosi', 'murah', 'cepat', 'fasilitas', 'tingkat', 'garda', 'jam', 'alat', 'siaga', 'masyarakat', 'cenderung', 'rumah', 'sakit', 'opsi', 'mudah', 'infrastruktur', 'kualitas', 'transparansi', 'biaya', 'prosedur', 'pasien', 'konsekuensi', 'finansial', 'prosedur', 'rutin', 'sarana', 'deteksi', 'indikasi', 'medis', 'operasi', 'komunikasi', 'tenaga', 'medis', 'kunci', 'edukasi', 'komprehensif', 'kontrol', 'bijak', 'indikasi', 'medis', 'tren', 'indikasi', 'medis', 'dana', 'masyarakat', 'mantan', 'sirkus', 'komisi', 'gelar', 'audiensi', 'mantan', 'sirkus', 'oriental', 'audiensi', 'rapat', 'dengar', 'mantan', 'sirkus', 'asasi', 'manusia', 'taman', 'safari', 'anggota', 'komisi', 'audiensi', 'siang', 'jam', 'forum', 'rapat', 'politikus', 'partai', 'bangsa', 'audiensi', 'aktif', 'aparat', 'hukum', 'audiensi', 'direktur', 'kriminal', 'panggil', 'eks', 'sirkus', 'ketua', 'komisi', 'kuasa', 'hukum', 'sirkus', 'panggil', 'kompleks', 'parlemen', 'kamis', 'korban', 'prioritas', 'jenis', 'hukum', 'berat', 'politikus', 'partai', 'mantan', 'sirkus', 'oriental', 'eksploitasi', 'asasi', 'manusia', 'asasi', 'manusia', 'tindak', 'eksploitasi', 'mantan', 'taman', 'safari', 'korban', 'hadir', 'perempuan', 'paruh', 'baya', 'kronologi', 'sirkus', 'bentuk', 'kondisi', 'sakit', 'menteri', 'cerita', 'korban', 'korban', 'korban', 'langkah', 'taman', 'safari', 'satwa', 'oriental', 'sirkus', 'pesan', 'media', 'massa', 'media', 'mesti', 'media', 'konvensional', 'televisi', 'koran', 'majalah', 'ekonomi', 'pengaruh', 'masyarakat', 'media', 'media', 'mesin', 'konteks', 'studi', 'ekonomi', 'politik', 'media', 'raksasa', 'digital', 'media', 'global', 'proses', 'revolusi', 'digital', 'penetrasi', 'batas', 'geografis', 'cepat', 'konstelasi', 'media', 'global', 'regional', 'pesat', 'media', 'serius', 'daya', 'hidup', 'media', 'indikasi', 'performa', 'industri', 'surat', 'kabar', 'harga', 'saham', 'surat', 'kabar', 'iklan', 'sirkulasi', 'berita', 'surat', 'kabar', 'gulung', 'tikar', 'frekuensi', 'volume', 'dunia', 'sisi', 'iklan', 'khalayak', 'radio', 'tren', 'tren', 'global', 'media', 'konvensional', 'surut', 'media', 'digital', 'media', 'digital', 'pesat', 'surplus', 'ekonomi', 'media', 'konvensional', 'media', 'digital', 'global', 'media', 'jurnalistik', 'mesin', 'surplus', 'ekonomi', 'media', 'konvensional', 'nasional', 'media', 'digital', 'global', 'lanskap', 'komunikasi', 'informasi', 'iklim', 'media', 'timpang', 'media', 'teknologi', 'model', 'khalayak', 'posisi', 'media', 'media', 'institusi', 'sosial', 'masyarakat', 'informasi', 'komunikasi', 'institusi', 'bisnis', 'motif', 'ekonomi', 'media', 'proses', 'informasi', 'media', 'subyek', 'hukum', 'media', 'hadir', 'pengaruh', 'daya', 'hidup', 'media', 'konteks', 'iklim', 'timpang', 'media', 'media', 'media', 'fungsi', 'media', 'ruang', 'publik', 'forum', 'diskusi', 'ruang', 'publik', 'komunikasi', 'sarana', 'artikulasi', 'sarana', 'sikap', 'acuh', 'acuh', 'prasangka', 'buruk', 'ruang', 'publik', 'media', 'konvensional', 'media', 'konvensional', 'sistem', 'sistem', 'hukum', 'praktik', 'media', 'antisipasi', 'komunikasi', 'sulit', 'anonimitas', 'ambiguitas', 'posisi', 'ruang', 'publik', 'ruang', 'privat', 'ambivalensi', 'komunikasi', 'massa', 'komunikasi', 'sifat', 'media', 'transnasional', 'fungsi', 'ruang', 'komunikasi', 'tuntas', 'pajak', 'imunitas', 'sengketa', 'eksistensi', 'media', 'konvensional', 'media', 'jurnalistik', 'prioritas', 'demokrasi', 'relevan', 'masyarakat', 'butuh', 'profesional', 'mesti', 'informasi', 'proporsional', 'profesional', 'profesional', 'jurnalistik', 'eksistensi', 'media', 'massa', 'konvensional', 'strategis', 'konteks', 'demokratisasi', 'ruang', 'publik', 'eksistensi', 'media', 'jurnalistik', 'makna', 'sisi', 'media', 'jurnalistik', 'perilaku', 'masyarakat', 'informasi', 'digital', 'problem', 'masyarakat', 'informasi', 'media', 'jurnalistik', 'standar', 'jurnalisme', 'baku', 'mode', 'informasi', 'serba', 'instan', 'cepat', 'akurasi', 'ruang', 'publik', 'media', 'jurnalistik', 'habitat', 'media', 'jurnalistik', 'mesti', 'jurnalisme', 'mesti', 'hadir', 'proteksi', 'komitmen', 'iklim', 'bisnis', 'media', 'sehat', 'mesin', 'media', 'media', 'mesti', 'bayar', 'pajak', 'media', 'bayar', 'pajak', 'media', 'nasional', 'mesti', 'royalti', 'cipta', 'konten', 'media', 'konten', 'media', 'media', 'hukum', 'syarat', 'bisnis', 'media', 'media', 'eksistensi', 'media', 'massa', 'nasional', 'iklim', 'usaha', 'ilusi', 'negara', 'konferensi', 'sikap', 'tunduk', 'polarisasi', 'perang', 'dingin', 'netralitas', 'strategi', 'netralitas', 'bentuk', 'logika', 'dominasi', 'tanggung', 'sejarah', 'lahir', 'tekad', 'subyek', 'politik', 'tatanan', 'dunia', 'blok', 'dunia', 'polarisasi', 'ideologis', 'struktur', 'global', 'transformasi', 'dunia', 'bipolar', 'dunia', 'multipolar', 'muncul', 'sistem', 'ekonomi', 'politik', 'global', 'wajah', 'lanskap', 'negara', 'negara', 'global', 'struktur', 'relasi', 'timpang', 'teknologi', 'dagang', 'dinamika', 'presiden', 'tarif', 'persen', 'produk', 'dalih', 'industri', 'domestik', 'distribusi', 'pasar', 'tarif', 'persen', 'produk', 'produk', 'fiskal', 'perang', 'simbol', 'dominasi', 'kontrol', 'ekonomi', 'dunia', 'negara', 'negara', 'global', 'sanksi', 'alat', 'ekonomi', 'senjata', 'geopolitik', 'negara', 'negara', 'struktural', 'biaya', 'ekspor', 'nilai', 'tukar', 'pasar', 'pisau', 'netralitas', 'posisi', 'negara', 'daya', 'tawar', 'eksternal', 'dunia', 'logika', 'sanksi', 'tarif', 'ruang', 'posisi', 'bicara', 'ideologis', 'perang', 'dingin', 'netralitas', 'strategis', 'nasional', 'domestik', 'pragmatisme', 'visi', 'jangka', 'oportunisme', 'lanskap', 'mitra', 'negara', 'politik', 'konkret', 'janji', 'retoris', 'insentif', 'ekonomi', 'ideologis', 'lembaga', 'alternatif', 'dagang', 'digital', 'cair', 'lembaga', 'global', 'bank', 'dunia', 'kerap', 'agenda', 'liberalisasi', 'miliar', 'proyek', 'sektor', 'energi', 'manufaktur', 'tenggara', 'produksi', 'ekspansi', 'sektor', 'panel', 'surya', 'respons', 'tarif', 'proyek', 'kereta', 'energi', 'proyek', 'global', 'target', 'miliar', 'respons', 'pengaruh', 'realitas', 'strategi', 'global', 'netralitas', 'steril', 'manuver', 'ganda', 'aktif', 'komitmen', 'posisi', 'dunia', 'bentuk', 'negara', 'posisi', 'geografis', 'ekonomi', 'rawan', 'strategis', 'diplomasi', 'cerdas', 'diversifikasi', 'mitra', 'arah', 'negara', 'portofolio', 'dinamis', 'relasi', 'arah', 'konflik', 'kalkulasi', 'titik', 'mitra', 'agenda', 'nasional', 'kuat', 'negara', 'global', 'orbit', 'posisi', 'tawar', 'investasi', 'riset', 'teknologi', 'internasional', 'siklus', 'berangkat', 'fondasi', 'domestik', 'narasi', 'global', 'isu', 'transisi', 'energi', 'tatanan', 'internasional', 'negara', 'negara', 'negara', 'global', 'transisi', 'hijau', 'finansial', 'bentuk', 'kolonialisme', 'karbon', 'arsitektur', 'digital', 'global', 'oligopoli', 'ulang', 'aliansi', 'ulang', 'makna', 'netralitas', 'dunia', 'diam', 'suara', 'keras', 'netralitas', 'aktif', 'netralitas', 'bentuk', 'pasif', 'sistem', 'timur', 'sistem', 'ruang', 'mitra', 'strategis', 'bentuk', 'tunggal', 'global', 'meja', 'global', 'agenda', 'dunia', 'kuat', 'berani', 'ulang', 'esok', 'proyek', 'netralitas', 'global', 'latar', 'narasi', 'cerita', 'bahasa', 'direktur', 'eksekutif', 'dosen', 'internasional', 'ganjing', 'isu', 'evakuasi', 'warga', 'pekan', 'evakuasi', 'warga', 'yatim', 'piatu', 'gelombang', 'presiden', 'negara', 'timur', 'konsultasi', 'evakuasi', 'warga', 'negara', 'presiden', 'peran', 'kunci', 'isu', 'uni', 'emirat', 'presiden', 'timur', 'misi', 'isu', 'presiden', 'presiden', 'presiden', 'isu', 'presiden', 'presiden', 'kuat', 'isu', 'niat', 'tulus', 'presiden', 'rakyat', 'evakuasi', 'warga', 'misi', 'tulus', 'sikap', 'penuh', 'hati', 'presiden', 'evakuasi', 'warga', 'gencar', 'agenda', 'relokasi', 'warga', 'juta', 'jiwa', 'negara', 'warga', 'presiden', 'relokasi', 'warga', 'dalih', 'wilayah', 'jalur', 'hancur', 'lebur', 'akibat', 'perang', 'layak', 'huni', 'wilayah', 'jalur', 'pusat', 'pariwisata', 'timur', 'jejak', 'kota', 'penuh', 'semangat', 'inisiatif', 'relokasi', 'warga', 'presiden', 'ideologi', 'kolonial', 'kaum', 'wilayah', 'luas', 'sungai', 'sungai', 'direktorat', 'relokasi', 'warga', 'agenda', 'relokasi', 'warga', 'bandara', 'udara', 'jalur', 'titik', 'tolak', 'proses', 'relokasi', 'warga', 'negara', 'komunikasi', 'negara', 'relokasi', 'warga', 'nama', 'relokasi', 'warga', 'prioritas', 'relokasi', 'warga', 'jalur', 'geografis', 'jalur', 'presiden', 'timur', 'lobi', 'relokasi', 'warga', 'negara', 'ekonomi', 'relokasi', 'warga', 'rahasia', 'relokasi', 'warga', 'negara', 'negara', 'keras', 'ide', 'relokasi', 'warga', 'negara', 'negara', 'liga', 'relokasi', 'warga', 'negara', 'relokasi', 'warga', 'bangsa', 'liga', 'posisi', 'politik', 'kuat', 'relokasi', 'warga', 'liga', 'relokasi', 'warga', 'liga', 'relokasi', 'warga', 'relokasi', 'warga', 'cepat', 'lambat', 'paksa', 'sukarela', 'isu', 'relokasi', 'warga', 'bola', 'panas', 'sengit', 'agenda', 'panggung', 'politik', 'timur', 'agenda', 'relokasi', 'warga', 'agenda', 'relokasi', 'warga', 'liga', 'tulus', 'evakuasi', 'warga', 'waspada', 'agenda', 'timur', 'waspada', 'program', 'evakuasi', 'program', 'relokasi', 'warga', 'jalur', 'tanah', 'air', 'warga', 'jalur', 'warga', 'tanah', 'air', 'evakuasi', 'diplomatik', 'diplomatik', 'palang', 'merah', 'internasional', 'komisi', 'negara', 'diplomatik', 'internasional', 'rendah', 'internasional', 'aksi', 'senjata', 'masyarakat', 'internasional', 'perang', 'jalur', 'resolusi', 'senjata', 'jalur', 'tampil', 'negara', 'hukum', 'muka', 'bumi', 'program', 'warga', 'risiko', 'relokasi', 'proyek', 'tradisi', 'simbol', 'interaksi', 'manusia', 'aktivitas', 'sederhana', 'penuh', 'individu', 'harmoni', 'masyarakat', 'modern', 'tradisi', 'sejarah', 'raja', 'gusti', 'abad', 'sasak', 'lombok', 'raja', 'tradisi', 'cerita', 'masyarakat', 'raja', 'prajurit', 'wadah', 'istirahat', 'solidaritas', 'prajurit', 'status', 'budaya', 'upacara', 'adat', 'acara', 'tradisi', 'duduk', 'nasi', 'lauk', 'pauk', 'nampan', 'serakah', 'nilai', 'erat', 'tradisi', 'tradisi', 'istilah', 'nama', 'acara', 'kenduri', 'adat', 'daun', 'pisang', 'wadah', 'nasi', 'lauk', 'pauk', 'sayur', 'sambal', 'khas', 'daerah', 'hasil', 'bumi', 'doa', 'tradisi', 'dimensi', 'spiritual', 'masyarakat', 'syukur', 'usia', 'status', 'sosial', 'nilai', 'syukur', 'rezeki', 'inti', 'tradisi', 'masyarakat', 'tradisional', 'solidaritas', 'individu', 'nilai', 'nilai', 'nikmat', 'tanggung', 'sejati', 'zaman', 'tradisi', 'gaya', 'hidup', 'modern', 'cenderung', 'individualis', 'tradisi', 'masyarakat', 'generasi', 'muda', 'porsi', 'nilai', 'tradisi', 'perlahan', 'aspek', 'higienis', 'praktik', 'kerap', 'tradisi', 'nilai', 'nilai', 'metode', 'budaya', 'tradisi', 'budaya', 'filosofi', 'hidup', 'harmoni', 'tradisi', 'langkah', 'identitas', 'budaya', 'simbol', 'budaya', 'alat', 'sosial', 'komunitas', 'tradisi', 'simbol', 'kuat', 'syukur', 'tradisi', 'komunitas', 'muda', 'modernisasi', 'aktivitas', 'sederhana', 'apresiasi', 'nilai', 'nilai', 'pudar', 'mari', 'semangat', 'tradisi', 'sejati', 'syukur', 'konseling', 'peran', 'strategis', 'konseling', 'siswa', 'suryani', 'materi', 'beliau', 'guru', 'konseling', 'strategi', 'sistem', 'peran', 'didik', 'siswa', 'didik', 'konseling', 'nilai', 'moral', 'fokus', 'sistem', 'generasi', 'cerdas', 'akademis', 'integritas', 'nilai', 'nilai', 'moral', 'kuat', 'globalisasi', 'penuh', 'siswa', 'situasi', 'sikap', 'perilaku', 'positif', 'konseling', 'peran', 'konseling', 'siswa', 'akademis', 'sarana', 'proses', 'siswa', 'nilai', 'nilai', 'moral', 'sosial', 'spiritual', 'konselor', 'siswa', 'potensi', 'sosial', 'suryani', 'guru', 'guru', 'kompleks', 'kualitas', 'skor', 'kualitas', 'daerah', 'wilayah', 'akses', 'siswa', 'kualitas', 'distribusi', 'guru', 'guru', 'guru', 'mental', 'siswa', 'siswa', 'psikologis', 'depresi', 'akademis', 'sosial', 'fenomena', 'sekolah', 'isu', 'serius', 'mental', 'siswa', 'peran', 'guru', 'konseling', 'isu', 'isu', 'dasar', 'langkah', 'strategis', 'peran', 'guru', 'konseling', 'mentor', 'siswa', 'guru', 'konseling', 'aktif', 'siswa', 'sekolah', 'signifikan', 'guru', 'mandiri', 'guru', 'konseling', 'nilai', 'nilai', 'guru', 'komunikasi', 'manajemen', 'tim', 'guru', 'mental', 'psikologis', 'siswa', 'psikologis', 'didik', 'percaya', 'sosial', 'akademik', 'guru', 'minat', 'bakat', 'guru', 'sekolah', 'nyaman', 'guru', 'perilaku', 'sekolah', 'perilaku', 'laki', 'laki', 'perempuan', 'guru', 'kelompok', 'siswa', 'tingkat', 'siswa', 'preventif', 'simfoni', 'tren', 'tim', 'ekosistem', 'tugas', 'kolaborasi', 'tua', 'masyarakat', 'tua', 'komunitas', 'guru', 'konseling', 'siswa', 'buku', 'sastrawan', 'wafat', 'tradisi', 'toko', 'buku', 'karya', 'global', 'buku', 'cipta', 'budaya', 'momen', 'reflektif', 'ulang', 'manusia', 'modern', 'buku', 'cermin', 'zaman', 'jendela', 'lanskap', 'digital', 'hiruk', 'muncul', 'paradoks', 'masyarakat', 'dunia', 'buku', 'fisik', 'buku', 'fisik', 'digital', 'serikat', 'buku', 'cetak', 'muda', 'buku', 'fisik', 'bau', 'kertas', 'tekstur', 'halaman', 'teori', 'fisik', 'kognitif', 'buku', 'fisik', 'makna', 'layar', 'digital', 'cenderung', 'dangkal', 'digitalisasi', 'buku', 'fisik', 'buku', 'digital', 'digitalisasi', 'masif', 'tingkat', 'daya', 'konsentrasi', 'survei', 'masyarakat', 'buku', 'fisik', 'buku', 'fisik', 'nilai', 'psikologis', 'aspek', 'koleksi', 'buku', 'psikologi', 'kognitif', 'interaksi', 'fisik', 'objek', 'retensi', 'buku', 'cetak', 'efektif', 'akademik', 'konsentrasi', 'cocok', 'medium', 'aksesibilitas', 'kualitas', 'efektivitas', 'minat', 'baca', 'pasar', 'buku', 'digital', 'tumbuh', 'minat', 'buku', 'cetak', 'akademisi', 'nasional', 'mahasiswa', 'mudah', 'buku', 'fisik', 'tingkat', 'rendah', 'survei', 'peringkat', 'negara', 'uis', 'peringkat', 'negara', 'tingkat', 'negara', 'negara', 'tetangga', 'tenggara', 'faktor', 'minat', 'sarana', 'prasarana', 'peran', 'keluarga', 'minim', 'aktivitas', 'pengaruh', 'negatif', 'televisi', 'pintar', 'remaja', 'multidimensi', 'akses', 'buku', 'timpang', 'daerah', 'bahan', 'budaya', 'lisan', 'dominan', 'tradisi', 'baca', 'teknis', 'praktik', 'sosial', 'ramah', 'harga', 'buku', 'kondisi', 'jurnal', 'jurnal', 'ilmiah', 'nasional', 'ekosistem', 'keluarga', 'sekolah', 'teori', 'ekologi', 'konteks', 'interaksi', 'individu', 'mikro', 'keluarga', 'sekolah', 'minat', 'program', 'merdeka', 'teknologi', 'digital', 'budaya', 'buku', 'fisik', 'esensi', 'kabar', 'tren', 'masyarakat', 'tingkat', 'gemar', 'kategori', 'hasil', 'keras', 'nasional', 'daerah', 'akses', 'buku', 'kualitas', 'buku', 'seremoni', 'buku', 'fisik', 'digital', 'jendela', 'dunia', 'lekang', 'digital', 'buku', 'fisik', 'hakikat', 'hati', 'utuh', 'halaman', 'sejarah', 'cerah', 'buku', 'jembatan',

In [ ]:
# ========== EVALUASI ==========
from collections import defaultdict
import numpy as np

# Mean Word Count
df['word_count'] = df['isi_clean'].apply(lambda x: len(x.split()))
mean_word_count = df['word_count'].mean()
print(f'\nMean Word Count: {mean_word_count:.2f}')

# Understemming Index
total_kata = len(words)
understemmed = len(list_not_in_kamus)
understemming_index = understemmed / total_kata
print(f'Understemming Index: {understemming_index:.4f}')

# Overstemming Index
akar_dict = defaultdict(int)
for w in AKAR_KATA:
    akar_dict[w] += 1

overstemmed = sum([v - 1 for v in akar_dict.values() if v > 1])
overstemming_index = overstemmed / len(AKAR_KATA) if len(AKAR_KATA) else 0
print(f'Overstemming Index: {overstemming_index:.4f}')

Mean Word Count: 740.83
Understemming Index: 0.0458
Overstemming Index: 0.8752